---
- name: install users
  hosts: dev
  vars_files:
    - user_list.yml
  tasks:
    - vars:
        password: "{{lookup('password',('password-')+item.name+' length=6')}}"
      name: create users
      ansible.builtin.user:
        name: "{{item.name}}"
        state: present
        uid: "{{item.id}}"
        password: "{{password|password_hash('sha256')}}"
        comment: "{{item.first | capitalize+' '+item.middle | capitalize+' '+item.last | capitalize}}"
      loop: "{{users}}"
